name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-27"

[placement]
mode = "smart"

[ai]
binding = "AI"

[durable_objects]
bindings = [{ name = "Y_DURABLE_OBJECTS", class_name = "YDurableObjects" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["YDurableObjects"]

[observability]
enabled = true

[[r2_buckets]]
bucket_name = "litarchive"
preview_bucket_name = "litarchive-dev"
binding = "litarchive"

[env.dev]
name = "litarchive-dev"
r2_buckets = [
  { binding = "litarchive", bucket_name = "litarchive-dev", preview_bucket_name = "litarchive-dev" },
]

[env.dev.ai]
binding = "AI"

[[env.dev.durable_objects.bindings]]
name = "Y_DURABLE_OBJECTS"
class_name = "YDurableObjects"
