name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-27"

[[r2_buckets]]
bucket_name = "litarchive"
preview_bucket_name = "litarchive-dev"
binding = "litarchive"

[env.dev]
name = "litarchive-dev"

r2_buckets = [
  { binding = "litarchive", bucket_name = "litarchive-dev", preview_bucket_name = "litarchive-dev" },
]
