name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-27"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL = "libsql://arm-lit-archive-musheghmov.turso.io"
DATABASE_AUTH_TOKEN = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDc1MTk2MzQsImlkIjoiNmQ2ZDViNDgtYzU1NC0xMWVlLTkzODYtZTI2ZDU1MjRlMzAxIn0.UR3R4dXdHUuxJ_awYSzuqqk080bR0E2VT1zHq_s6gkB0fmNL4Y7nQBWwGOcUQiOQaM9uu0u8wfiVAAAG33_UBw"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1

